[Android] Homework 2-1
EleonorManolovaAccedia/MyStore pull request #3
Opened 2023-05-29 15:49 UTC by EleonorManolovaAccedia

2023-06-01 17:39 UTC, yll090 requested changes

2023-06-01 17:39 UTC, yll090 commented on app/src/main/java/com/example/mystore/ui/login/LoginScreen.kt
> +        val errorBody = loginViewModel.response?.errorBody()?.string()
You should be able to safely do that in the viewModel instead. The view should just know about view-related stuff (navigation, changing views/showing errors based on the state of the *viewModel data*).  Try to refactor this so it uses just viewModel data.

2023-06-01 17:39 UTC, yll090 commented on app/src/main/java/com/example/mystore/ui/login/LoginScreen.kt
> +                    .padding(top = 150.dp),
No random numbers -- try to export them and reuse them. There are some others, look for those in the code and refactor them (no need to spam you with comments about it).

2023-06-13 17:59 UTC, gbuyukliev-accedia approved these changes

2023-06-13 17:59 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mystore/ui/login/LoginScreen.kt
>      val isValidEmail: (email: String) -> Boolean = { email ->
Will be cleaner if this was a `String` `extension function` in an `Extensions` file outside of this view.

2023-06-13 17:59 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mystore/ui/login/LoginScreen.kt
>      val validateFields: (email: String, password: String) -> Boolean = { email, password ->
That appears to be more of a business logic opposed to a UI one, thus its place should preferably be in the view model.

2023-06-13 17:59 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mystore/ui/login/LoginScreen.kt
> +                    modifier = Modifier.scale(3.5f),
All values should be exported somewhere. There shouldn't be anything hardcoded.

2023-06-13 17:59 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mystore/ui/login/LoginScreen.kt
> +                    contentDescription = "Background Image",
Should be exported as a string if your intention is to help visually impaired users and a `constant` if you want to use this property as a QA test tag. Otherwise, if you don't want to bother with that, just always assign it a `null`.

2023-06-13 17:59 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mystore/ui/login/LoginScreen.kt
> +                    shape = RoundedCornerShape(50)
All hardcoded values should be exported.

Also, you can extend shapes and add custom values just like you can do with `Type` for the typography. Make a `Shape.kt` file in the `theme` package and you can do things like this (just an example):

```
val Shapes = Shapes(
    small = RoundedCornerShape(8.dp),
    medium = RoundedCornerShape(10.dp),
    large = RoundedCornerShape(20.dp, 20.dp, 0.dp, 0.dp)
)
```

You then access it with `MatherialTheme.shapes...`.

2023-06-13 17:59 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mystore/ui/login/LoginScreen.kt
> +                        loginViewModel.response?.let {
The view model shouldn't expose the response directly to the view and the view shouldn't care about it.

Option 1 (bad one): Expose the model out of the response, not the response itself, i.e. a `user` object.

Option 2 (good one): Handle the response absolutely internally inside of the view model and make a state not for the response but rather for something that acts simply as a trigger for a UI change (navigation), such as a `isLoginSuccessful` boolean.

Ideally, in the view model your states should be either Kotlin's `StateFlow` objects or in some rare occasions - `SharedFlow` but as we are yet about to talk about them on the next lecture, if you can't get it to work with them, you can use a regular `mutableState` too for this homework.

2023-06-13 17:59 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mystore/ui/login/LoginScreen.kt
> +                        loginViewModel.response?.let {
Such computational non-UI observations should never happen in the middle of the UI. You should attach them to `LaunchedEffect`s that subscribe to the state you're interested in and place this `LaunchedEffect` up above the whole UI as you would do with `useEffect` in React.

2023-06-13 17:59 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mystore/ui/products/ProductDetailsScreen.kt
>                  Button(
This button can be reused alongside the other button as a shared reusable composable, parametrized in a way that can satisfy both scenarios.

2023-06-13 17:59 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mystore/ui/shared/CustomTopBar.kt
> +                        .size(40.dp)
All `dp` values on this screen should b exported as `dimens`.

2023-06-13 17:59 UTC, gbuyukliev-accedia commented on app/src/main/java/com/example/mystore/ui/shared/RatingBar.kt
> +    stars: Int = 5,
This 5 can be a `static const val` constant in a `Constants` file.

Edit: I just saw you even already have one there.

2023-06-16 18:00 UTC, merged